### PR TITLE
Add styling to storeManager

### PR DESCRIPTION
**Pull request by probuse**
This pull request is what was required to style storeManager's UI.
@codjoero @BarnaTB @EmmellaBeatrice @masete @bekeplar @habatkasa @mwinel @fahadmak @RLubwama
Please review and give feedback on UI.
Thank you.

### CODE REVIEW

**Comment by patrickf949** [comment]
@probuse 
*nice ui especially for the login
*Responsive enough except for the admin dashboard on a mobile device (some words get jumbled a bit)
*Almost everything required is available except for the available quantity of the product in stock

**Comment by probuse** [comment]
@patrickf949  Thank you for the review and feedback
The  available quantity of the product in stock is inside the product detail page, should i have put it somewhere different?

**Comment by patrickf949** [comment]
@probuse ts ok i've seen it, though it would mean the store attendant would have to check if its in stock every time before they add a product to a shoppers cart
I think it would help if it were also on the products page(where all products are) either before or after the price

**Comment by bekeplar** [comment]
your work is amazing

**Comment by mariamiah** [comment]
Work looks great

**Comment by probuse** [comment]
@patrickf949 I used your feed back to improve my app
Added products in stock, and an out of stock label.
Thanks for the feedback

**Pull request merged**
